export const data = JSON.parse("{\"key\":\"v-7e70cc5c\",\"path\":\"/java/04.%E5%BC%82%E5%B8%B8.html\",\"title\":\"04.异常\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"04.异常\",\"index\":true,\"category\":[\"java\"],\"summary\":\"04.异常 1. 异常继承体系 Java中异常体系的核心类是Throwable，它有两个子类Error和Exception。 Error代表一些非常严重的错误。我们一般不必特意在代码中处理他们。 Exception相当于一些小错误。可以用来提示我们出现了什么问题。我们后面主要讲的就是Exception。 异常主要分两种： 1. 运行时异常（编译期间不会去做检\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.lovecode.icu/java/04.%E5%BC%82%E5%B8%B8.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"菜鸡的自我救赎\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"04.异常\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"1. 异常继承体系\",\"slug\":\"_1-异常继承体系\",\"link\":\"#_1-异常继承体系\",\"children\":[]},{\"level\":2,\"title\":\"2. 异常处理\",\"slug\":\"_2-异常处理\",\"link\":\"#_2-异常处理\",\"children\":[{\"level\":3,\"title\":\"2.1 throws声明抛出异常\",\"slug\":\"_2-1-throws声明抛出异常\",\"link\":\"#_2-1-throws声明抛出异常\",\"children\":[]},{\"level\":3,\"title\":\"2.2 try...catch抓取异常\",\"slug\":\"_2-2-try-catch抓取异常\",\"link\":\"#_2-2-try-catch抓取异常\",\"children\":[]}]},{\"level\":2,\"title\":\"3. 自定义异常\",\"slug\":\"_3-自定义异常\",\"link\":\"#_3-自定义异常\",\"children\":[]},{\"level\":2,\"title\":\"4. 异常的作用\",\"slug\":\"_4-异常的作用\",\"link\":\"#_4-异常的作用\",\"children\":[]}],\"readingTime\":{\"minutes\":2.9,\"words\":871},\"filePathRelative\":\"java/04.异常.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
